POST http://localhost:5000/DataContract.asmx
Content-Type: text/xml; charset=utf-8
SOAPAction: http://tempuri.org/loginMethod

<?xml version="1.0" encoding="utf-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="https://payment.fairfinansman.com.tr/">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:Request>
         <tem:username2>YourUsername2</tem:username2>
         <tem:password2>YourPassword2</tem:password2>
         <tem:anotherRequest>
            <tem:password>YourPassword</tem:password>
            <tem:username>YourUsername</tem:username>
         </tem:anotherRequest>
      </tem:Request>
   </soapenv:Body>
</soapenv:Envelope>

POST http://localhost:5000/DataContract.asmx
Content-Type: text/xml; charset=utf-8
SOAPAction: https://payment.fairfinansman.com.tr/reconciliateRequest

<?xml version="1.0" encoding="utf-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="https://payment.fairfinansman.com.tr/">
  <soapenv:Header/>
  <soapenv:Body>
    <tem:Request>
      <tem:arg0>
        <tem:reconDate>2025-09-04</tem:reconDate>
        <tem:reconType>Daily</tem:reconType>
        # <tem:bankId>10</tem:bankId>
        # <tem:bankUserName>harun korkmaz</tem:bankUserName>
        # <tem:companyId>12345</tem:companyId>
        # <tem:sessionId>ABCDEF-123456</tem:sessionId>
      </tem:arg0>
    </tem:Request>
  </soapenv:Body>
</soapenv:Envelope>`