//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// xscgen --namespace PaymentGatewayDotnet.PaymentGeneratedModels --output PaymentGeneratedModels .\xsd\PaymentApi.xsd

using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Xml.Schema;
using System.Xml.Serialization;

namespace SoapCalculator.PaymentGeneratedModels
{
    
    
    [GeneratedCode("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("giveAutoPaymentRequest", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRootAttribute("giveAutoPaymentRequest", Namespace="https://payment.fairfinansman.com.tr/")]
    public partial class GiveAutoPaymentRequest
    {
        
        [XmlElementAttribute("arg0", Form=XmlSchemaForm.Unqualified)]
        public AutoPaymentApiInput Arg0 { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("autoPaymentApiInput", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class AutoPaymentApiInput : BaseApiInput
    {
        
        [XmlElement("autoPaymentDate", Form=XmlSchemaForm.Unqualified)]
        public string AutoPaymentDate { get; set; }
        
        [XmlElementAttribute("autoPaymentTypeId", Form=XmlSchemaForm.Unqualified)]
        public string AutoPaymentTypeId { get; set; }
        
        [XmlElementAttribute("channelId", Form=XmlSchemaForm.Unqualified)]
        public string ChannelId { get; set; }
        
        [XmlElementAttribute("contractId", Form=XmlSchemaForm.Unqualified)]
        public string ContractId { get; set; }
        
        [XmlElementAttribute("nameSurname", Form=XmlSchemaForm.Unqualified)]
        public string NameSurname { get; set; }
        
        [XmlElementAttribute("reconDate", Form=XmlSchemaForm.Unqualified)]
        public string ReconDate { get; set; }
        
        [XmlElementAttribute("tckn", Form=XmlSchemaForm.Unqualified)]
        public string Tckn { get; set; }
        
        [XmlElementAttribute("transactionId", Form=XmlSchemaForm.Unqualified)]
        public string TransactionId { get; set; }
        
        [XmlElementAttribute("vkn", Form=XmlSchemaForm.Unqualified)]
        public string Vkn { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("baseApiInput", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlIncludeAttribute(typeof(AutoPaymentApiInput))]
    [XmlIncludeAttribute(typeof(CancelAutoPaymentApiInput))]
    [XmlIncludeAttribute(typeof(GetOpenInvoicesApiInput))]
    [XmlIncludeAttribute(typeof(GetOpenInvoicesWithAutoPaymentApiInput))]
    [XmlIncludeAttribute(typeof(PaymentApiInput))]
    [XmlIncludeAttribute(typeof(QueryAutoPaymentApiInput))]
    [XmlIncludeAttribute(typeof(ReconciliationApiInput))]
    public partial class BaseApiInput
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("bankId", Form=XmlSchemaForm.Unqualified)]
        public int BankId { get; set; }
        
        [XmlElementAttribute("bankUserName", Form=XmlSchemaForm.Unqualified)]
        public string BankUserName { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("companyId", Form=XmlSchemaForm.Unqualified)]
        public int CompanyId { get; set; }
        
        [XmlElementAttribute("sessionId", Form=XmlSchemaForm.Unqualified)]
        public string SessionId { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("giveAutoPaymentResponse", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("giveAutoPaymentResponse", Namespace="https://payment.fairfinansman.com.tr/")]
    public partial class GiveAutoPaymentResponse
    {
        
        [XmlElementAttribute("return", Form=XmlSchemaForm.Unqualified)]
        public BaseApiOutput Return { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("baseApiOutput", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlIncludeAttribute(typeof(GetOpenInvoicesApiOutput))]
    [XmlIncludeAttribute(typeof(GetOpenInvoicesWithAutoPaymentApiOutput))]
    [XmlIncludeAttribute(typeof(LoginResponse))]
    [XmlIncludeAttribute(typeof(QueryAutoPaymentApiOutput))]
    [XmlIncludeAttribute(typeof(ReconciliationApiOutput))]
    [XmlIncludeAttribute(typeof(ReconciliationDetailApiOutput))]
    public partial class BaseApiOutput
    {
        
        [Required(AllowEmptyStrings=true)]
        [XmlElementAttribute("resultCode", Form=XmlSchemaForm.Unqualified)]
        public int ResultCode { get; set; }
        
        [XmlElementAttribute("resultDesc", Form=XmlSchemaForm.Unqualified)]
        public string ResultDesc { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("getOpenInvoicesRequest", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("getOpenInvoicesRequest", Namespace="https://payment.fairfinansman.com.tr/")]
    public partial class GetOpenInvoicesRequest
    {
        
        [XmlElementAttribute("arg0", Form=XmlSchemaForm.Unqualified)]
        public GetOpenInvoicesApiInput Arg0 { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("getOpenInvoicesApiInput", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class GetOpenInvoicesApiInput : BaseApiInput
    {
        
        [XmlElementAttribute("channelId", Form=XmlSchemaForm.Unqualified)]
        public string ChannelId { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("creditCount", Form=XmlSchemaForm.Unqualified)]
        public int CreditCount { get; set; }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("invoiceCount", Form=XmlSchemaForm.Unqualified)]
        public int InvoiceCount { get; set; }
        
        [XmlElementAttribute("paymentPeriod", Form=XmlSchemaForm.Unqualified)]
        public string PaymentPeriod { get; set; }
        
        [XmlElementAttribute("queryKey", Form=XmlSchemaForm.Unqualified)]
        public string QueryKey { get; set; }
        
        [XmlElementAttribute("queryValue", Form=XmlSchemaForm.Unqualified)]
        public string QueryValue { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("getOpenInvoicesResponse", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("getOpenInvoicesResponse", Namespace="https://payment.fairfinansman.com.tr/")]
    public partial class GetOpenInvoicesResponse
    {
        
        [XmlElementAttribute("return", Form=XmlSchemaForm.Unqualified)]
        public GetOpenInvoicesApiOutput Return { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("getOpenInvoicesApiOutput", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class GetOpenInvoicesApiOutput : BaseApiOutput
    {
        
        [XmlElementAttribute("contractCount", Form=XmlSchemaForm.Unqualified)]
        public int ContractCount { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ContractCount property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool ContractCountSpecified { get; set; }
        
        [XmlElementAttribute("subscriberId", Form=XmlSchemaForm.Unqualified)]
        public string SubscriberId { get; set; }
        
        [XmlElementAttribute("isSubscriberMatch", Form=XmlSchemaForm.Unqualified)]
        public bool IsSubscriberMatch { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IsSubscriberMatch property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool IsSubscriberMatchSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<ContractApiOutput> _contractList;
        
        [XmlArrayAttribute("contractList", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("contract", Form=XmlSchemaForm.Unqualified, IsNullable=true)]
        public Collection<ContractApiOutput> ContractList
        {
            get
            {
                return _contractList;
            }
            private set
            {
                _contractList = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ContractList collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool ContractListSpecified
        {
            get
            {
                return (this.ContractList.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="GetOpenInvoicesApiOutput" /> class.</para>
        /// </summary>
        public GetOpenInvoicesApiOutput()
        {
            this._contractList = new Collection<ContractApiOutput>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("contractListApiOutput", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ContractListApiOutput
    {
        
        [XmlIgnoreAttribute()]
        private Collection<ContractApiOutput> _contract;
        
        [XmlElementAttribute("contract", Form=XmlSchemaForm.Unqualified, IsNullable=true)]
        public Collection<ContractApiOutput> Contract
        {
            get
            {
                return _contract;
            }
            private set
            {
                _contract = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Contract collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool ContractSpecified
        {
            get
            {
                return (this.Contract.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ContractListApiOutput" /> class.</para>
        /// </summary>
        public ContractListApiOutput()
        {
            this._contract = new Collection<ContractApiOutput>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("contractApiOutput", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ContractApiOutput
    {
        
        [XmlElementAttribute("contractId", Form=XmlSchemaForm.Unqualified)]
        public string ContractId { get; set; }
        
        [XmlElementAttribute("contractTypeId", Form=XmlSchemaForm.Unqualified)]
        public int ContractTypeId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ContractTypeId property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool ContractTypeIdSpecified { get; set; }
        
        [XmlElementAttribute("contractDate", Form=XmlSchemaForm.Unqualified)]
        public string ContractDate { get; set; }
        
        [XmlElementAttribute("totalInstallmentCount", Form=XmlSchemaForm.Unqualified)]
        public int TotalInstallmentCount { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TotalInstallmentCount property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool TotalInstallmentCountSpecified { get; set; }
        
        [XmlElementAttribute("description", Form=XmlSchemaForm.Unqualified)]
        public string Description { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<InvoiceApiInput> _invoiceList;
        
        [XmlArrayAttribute("invoiceList", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("invoice", Form=XmlSchemaForm.Unqualified, IsNullable=true)]
        public Collection<InvoiceApiInput> InvoiceList
        {
            get
            {
                return _invoiceList;
            }
            private set
            {
                _invoiceList = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the InvoiceList collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool InvoiceListSpecified
        {
            get
            {
                return (this.InvoiceList.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ContractApiOutput" /> class.</para>
        /// </summary>
        public ContractApiOutput()
        {
            this._invoiceList = new Collection<InvoiceApiInput>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("invoiceListApiInput", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class InvoiceListApiInput
    {
        
        [XmlIgnoreAttribute()]
        private Collection<InvoiceApiInput> _invoice;
        
        [XmlElementAttribute("invoice", Form=XmlSchemaForm.Unqualified, IsNullable=true)]
        public Collection<InvoiceApiInput> Invoice
        {
            get
            {
                return _invoice;
            }
            private set
            {
                _invoice = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Invoice collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool InvoiceSpecified
        {
            get
            {
                return (this.Invoice.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="InvoiceListApiInput" /> class.</para>
        /// </summary>
        public InvoiceListApiInput()
        {
            this._invoice = new Collection<InvoiceApiInput>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("invoiceApiInput", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class InvoiceApiInput
    {
        
        [XmlElementAttribute("contractId", Form=XmlSchemaForm.Unqualified)]
        public string ContractId { get; set; }
        
        [XmlElementAttribute("invoiceId", Form=XmlSchemaForm.Unqualified)]
        public int InvoiceId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the InvoiceId property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool InvoiceIdSpecified { get; set; }
        
        [XmlElementAttribute("subscriberId", Form=XmlSchemaForm.Unqualified)]
        public string SubscriberId { get; set; }
        
        [XmlElementAttribute("invoiceDate", Form=XmlSchemaForm.Unqualified)]
        public string InvoiceDate { get; set; }
        
        [XmlElementAttribute("dueDate", Form=XmlSchemaForm.Unqualified)]
        public string DueDate { get; set; }
        
        [XmlElementAttribute("paymentPeriod", Form=XmlSchemaForm.Unqualified)]
        public string PaymentPeriod { get; set; }
        
        [XmlElementAttribute("invoiceTypeId", Form=XmlSchemaForm.Unqualified)]
        public int InvoiceTypeId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the InvoiceTypeId property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool InvoiceTypeIdSpecified { get; set; }
        
        [XmlElementAttribute("installmentNumber", Form=XmlSchemaForm.Unqualified)]
        public int InstallmentNumber { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the InstallmentNumber property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool InstallmentNumberSpecified { get; set; }
        
        [XmlElementAttribute("nameSurname", Form=XmlSchemaForm.Unqualified)]
        public string NameSurname { get; set; }
        
        [XmlElementAttribute("amount", Form=XmlSchemaForm.Unqualified)]
        public decimal Amount { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Amount property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool AmountSpecified { get; set; }
        
        [XmlElementAttribute("description", Form=XmlSchemaForm.Unqualified)]
        public string Description { get; set; }
        
        [XmlElementAttribute("isPayable", Form=XmlSchemaForm.Unqualified)]
        public bool IsPayable { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IsPayable property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool IsPayableSpecified { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("reconciliateRequest", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("reconciliateRequest", Namespace="https://payment.fairfinansman.com.tr/")]
    public partial class ReconciliateRequest
    {
        
        [XmlElementAttribute("arg0", Form=XmlSchemaForm.Unqualified)]
        public ReconciliationApiInput Arg0 { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("reconciliationApiInput", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ReconciliationApiInput : BaseApiInput
    {
        
        [XmlElementAttribute("reconDate", Form=XmlSchemaForm.Unqualified)]
        public string ReconDate { get; set; }
        
        [XmlElementAttribute("reconType", Form=XmlSchemaForm.Unqualified)]
        public string ReconType { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("reconciliateResponse", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("reconciliateResponse", Namespace="https://payment.fairfinansman.com.tr/")]
    public partial class ReconciliateResponse
    {
        
        [XmlElementAttribute("return", Form=XmlSchemaForm.Unqualified)]
        public ReconciliationApiOutput Return { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("reconciliationApiOutput", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ReconciliationApiOutput : BaseApiOutput
    {
        
        [XmlElementAttribute("reconDate", Form=XmlSchemaForm.Unqualified)]
        public string ReconDate { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<ReconciliationEntryApiOutput> _reconciliationEntryList;
        
        [XmlElementAttribute("reconciliationEntryList", Form=XmlSchemaForm.Unqualified, IsNullable=true)]
        public Collection<ReconciliationEntryApiOutput> ReconciliationEntryList
        {
            get
            {
                return _reconciliationEntryList;
            }
            private set
            {
                _reconciliationEntryList = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ReconciliationEntryList collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool ReconciliationEntryListSpecified
        {
            get
            {
                return (this.ReconciliationEntryList.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ReconciliationApiOutput" /> class.</para>
        /// </summary>
        public ReconciliationApiOutput()
        {
            this._reconciliationEntryList = new Collection<ReconciliationEntryApiOutput>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("reconciliationEntryApiOutput", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ReconciliationEntryApiOutput
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("count", Form=XmlSchemaForm.Unqualified)]
        public long Count { get; set; }
        
        [XmlElementAttribute("sumAmount", Form=XmlSchemaForm.Unqualified)]
        public decimal SumAmount { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SumAmount property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool SumAmountSpecified { get; set; }
        
        [XmlElementAttribute("transactionType", Form=XmlSchemaForm.Unqualified)]
        public string TransactionType { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("completeReconciliationRequest", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("completeReconciliationRequest", Namespace="https://payment.fairfinansman.com.tr/")]
    public partial class CompleteReconciliationRequest
    {
        
        [XmlElementAttribute("arg0", Form=XmlSchemaForm.Unqualified)]
        public ReconciliationApiInput Arg0 { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("completeReconciliationResponse", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("completeReconciliationResponse", Namespace="https://payment.fairfinansman.com.tr/")]
    public partial class CompleteReconciliationResponse
    {
        
        [XmlElementAttribute("return", Form=XmlSchemaForm.Unqualified)]
        public BaseApiOutput Return { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("queryAutoPaymentRequest", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("queryAutoPaymentRequest", Namespace="https://payment.fairfinansman.com.tr/")]
    public partial class QueryAutoPaymentRequest
    {
        
        [XmlElementAttribute("arg0", Form=XmlSchemaForm.Unqualified)]
        public QueryAutoPaymentApiInput Arg0 { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("queryAutoPaymentApiInput", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class QueryAutoPaymentApiInput : BaseApiInput
    {
        
        [XmlElementAttribute("channelId", Form=XmlSchemaForm.Unqualified)]
        public string ChannelId { get; set; }
        
        [XmlElementAttribute("contractId", Form=XmlSchemaForm.Unqualified)]
        public string ContractId { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("queryAutoPaymentResponse", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("queryAutoPaymentResponse", Namespace="https://payment.fairfinansman.com.tr/")]
    public partial class QueryAutoPaymentResponse
    {
        
        [XmlElementAttribute("return", Form=XmlSchemaForm.Unqualified)]
        public QueryAutoPaymentApiOutput Return { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("queryAutoPaymentApiOutput", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class QueryAutoPaymentApiOutput : BaseApiOutput
    {
        
        [XmlElementAttribute("autoPaymentDate", Form=XmlSchemaForm.Unqualified)]
        public string AutoPaymentDate { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("payInvoiceRequest", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("payInvoiceRequest", Namespace="https://payment.fairfinansman.com.tr/")]
    [MessageContract(IsWrapped = false)]
    public partial class PayInvoiceRequest
    {
        
        [XmlElementAttribute("arg0", Form=XmlSchemaForm.Unqualified)]
        public PaymentApiInput Arg0 { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("paymentApiInput", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PaymentApiInput : BaseApiInput
    {
        
        [XmlElementAttribute("channelId", Form=XmlSchemaForm.Unqualified)]
        public string ChannelId { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<InvoiceApiInput> _invoiceList;
        
        [XmlArrayAttribute("invoiceList", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("invoice", Form=XmlSchemaForm.Unqualified, IsNullable=true)]
        public Collection<InvoiceApiInput> InvoiceList
        {
            get
            {
                return _invoiceList;
            }
            private set
            {
                _invoiceList = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the InvoiceList collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool InvoiceListSpecified
        {
            get
            {
                return (this.InvoiceList.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PaymentApiInput" /> class.</para>
        /// </summary>
        public PaymentApiInput()
        {
            this._invoiceList = new Collection<InvoiceApiInput>();
        }
        
        [XmlElementAttribute("paymentDate", Form=XmlSchemaForm.Unqualified)]
        public string PaymentDate { get; set; }
        
        [XmlElementAttribute("paymentTypeId", Form=XmlSchemaForm.Unqualified)]
        public string PaymentTypeId { get; set; }
        
        [XmlElementAttribute("reconDate", Form=XmlSchemaForm.Unqualified)]
        public string ReconDate { get; set; }
        
        [XmlElementAttribute("transactionId", Form=XmlSchemaForm.Unqualified)]
        public string TransactionId { get; set; }
        
        [XmlElementAttribute("subscriberId", Form=XmlSchemaForm.Unqualified)]
        public string SubscriberId { get; set; }
        
        [XmlElementAttribute("contractId", Form=XmlSchemaForm.Unqualified)]
        public string ContractId { get; set; }
        
        [XmlElementAttribute("earlySettlementAmount", Form=XmlSchemaForm.Unqualified)]
        public decimal EarlySettlementAmount { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the EarlySettlementAmount property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool EarlySettlementAmountSpecified { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("payInvoiceResponse", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("payInvoiceResponse", Namespace="https://payment.fairfinansman.com.tr/")]
    public partial class PayInvoiceResponse
    {
        
        [XmlElementAttribute("return", Form=XmlSchemaForm.Unqualified)]
        public BaseApiOutput Return { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("getOpenInvoicesWithAutoPaymentRequest", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("getOpenInvoicesWithAutoPaymentRequest", Namespace="https://payment.fairfinansman.com.tr/")]
    public partial class GetOpenInvoicesWithAutoPaymentRequest
    {
        
        [XmlElementAttribute("arg0", Form=XmlSchemaForm.Unqualified)]
        public GetOpenInvoicesWithAutoPaymentApiInput Arg0 { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("getOpenInvoicesWithAutoPaymentApiInput", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class GetOpenInvoicesWithAutoPaymentApiInput : BaseApiInput
    {
        
        [XmlElementAttribute("endDate", Form=XmlSchemaForm.Unqualified)]
        public string EndDate { get; set; }
        
        [XmlElementAttribute("startDate", Form=XmlSchemaForm.Unqualified)]
        public string StartDate { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("getOpenInvoicesWithAutoPaymentResponse", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("getOpenInvoicesWithAutoPaymentResponse", Namespace="https://payment.fairfinansman.com.tr/")]
    public partial class GetOpenInvoicesWithAutoPaymentResponse
    {
        
        [XmlElementAttribute("return", Form=XmlSchemaForm.Unqualified)]
        public GetOpenInvoicesWithAutoPaymentApiOutput Return { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("getOpenInvoicesWithAutoPaymentApiOutput", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class GetOpenInvoicesWithAutoPaymentApiOutput : BaseApiOutput
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("invoiceCount", Form=XmlSchemaForm.Unqualified)]
        public int InvoiceCount { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<InvoiceApiInput> _invoiceList;
        
        [XmlArrayAttribute("invoiceList", Form=XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("invoice", Form=XmlSchemaForm.Unqualified, IsNullable=true)]
        public Collection<InvoiceApiInput> InvoiceList
        {
            get
            {
                return _invoiceList;
            }
            private set
            {
                _invoiceList = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the InvoiceList collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool InvoiceListSpecified
        {
            get
            {
                return (this.InvoiceList.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="GetOpenInvoicesWithAutoPaymentApiOutput" /> class.</para>
        /// </summary>
        public GetOpenInvoicesWithAutoPaymentApiOutput()
        {
            this._invoiceList = new Collection<InvoiceApiInput>();
        }
        
        [XmlElementAttribute("sumAmount", Form=XmlSchemaForm.Unqualified)]
        public double SumAmount { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SumAmount property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool SumAmountSpecified { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("cancelAutoPaymentRequest", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("cancelAutoPaymentRequest", Namespace="https://payment.fairfinansman.com.tr/")]
    public partial class CancelAutoPaymentRequest
    {
        
        [XmlElementAttribute("arg0", Form=XmlSchemaForm.Unqualified)]
        public CancelAutoPaymentApiInput Arg0 { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("cancelAutoPaymentApiInput", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class CancelAutoPaymentApiInput : BaseApiInput
    {
        
        [XmlElementAttribute("autoPaymentDate", Form=XmlSchemaForm.Unqualified)]
        public string AutoPaymentDate { get; set; }
        
        [XmlElementAttribute("channelId", Form=XmlSchemaForm.Unqualified)]
        public string ChannelId { get; set; }
        
        [XmlElementAttribute("reconDate", Form=XmlSchemaForm.Unqualified)]
        public string ReconDate { get; set; }
        
        [XmlElementAttribute("transactionId", Form=XmlSchemaForm.Unqualified)]
        public string TransactionId { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("cancelAutoPaymentResponse", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("cancelAutoPaymentResponse", Namespace="https://payment.fairfinansman.com.tr/")]
    public partial class CancelAutoPaymentResponse
    {
        
        [XmlElementAttribute("return", Form=XmlSchemaForm.Unqualified)]
        public BaseApiOutput Return { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("detailedReconciliationRequest", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("detailedReconciliationRequest", Namespace="https://payment.fairfinansman.com.tr/")]
    public partial class DetailedReconciliationRequest
    {
        
        [XmlElementAttribute("arg0", Form=XmlSchemaForm.Unqualified)]
        public ReconciliationApiInput Arg0 { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("detailedReconciliationResponse", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("detailedReconciliationResponse", Namespace="https://payment.fairfinansman.com.tr/")]
    public partial class DetailedReconciliationResponse
    {
        
        [XmlElementAttribute("return", Form=XmlSchemaForm.Unqualified)]
        public ReconciliationDetailApiOutput Return { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("reconciliationDetailApiOutput", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ReconciliationDetailApiOutput : BaseApiOutput
    {
        
        [XmlElementAttribute("reconDate", Form=XmlSchemaForm.Unqualified)]
        public string ReconDate { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<ReconciliationEntryDetail> _reconciliationEntryDetailList;
        
        [XmlElementAttribute("reconciliationEntryDetailList", Form=XmlSchemaForm.Unqualified, IsNullable=true)]
        public Collection<ReconciliationEntryDetail> ReconciliationEntryDetailList
        {
            get
            {
                return _reconciliationEntryDetailList;
            }
            private set
            {
                _reconciliationEntryDetailList = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ReconciliationEntryDetailList collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool ReconciliationEntryDetailListSpecified
        {
            get
            {
                return (this.ReconciliationEntryDetailList.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ReconciliationDetailApiOutput" /> class.</para>
        /// </summary>
        public ReconciliationDetailApiOutput()
        {
            this._reconciliationEntryDetailList = new Collection<ReconciliationEntryDetail>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("reconciliationEntryDetail", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ReconciliationEntryDetail
    {
        
        [XmlElementAttribute("contractId", Form=XmlSchemaForm.Unqualified)]
        public string ContractId { get; set; }
        
        [XmlElementAttribute("subscriberId", Form=XmlSchemaForm.Unqualified)]
        public string SubscriberId { get; set; }
        
        [XmlElementAttribute("dueDate", Form=XmlSchemaForm.Unqualified)]
        public string DueDate { get; set; }
        
        [XmlElementAttribute("invoiceId", Form=XmlSchemaForm.Unqualified)]
        public int InvoiceId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the InvoiceId property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool InvoiceIdSpecified { get; set; }
        
        [XmlElementAttribute("txDate", Form=XmlSchemaForm.Unqualified)]
        public string TxDate { get; set; }
        
        [XmlElementAttribute("channelId", Form=XmlSchemaForm.Unqualified)]
        public string ChannelId { get; set; }
        
        [XmlElementAttribute("reconDate", Form=XmlSchemaForm.Unqualified)]
        public string ReconDate { get; set; }
        
        [XmlElementAttribute("transactionId", Form=XmlSchemaForm.Unqualified)]
        public string TransactionId { get; set; }
        
        [XmlElementAttribute("amount", Form=XmlSchemaForm.Unqualified)]
        public decimal Amount { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Amount property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool AmountSpecified { get; set; }
        
        [XmlElementAttribute("transactionType", Form=XmlSchemaForm.Unqualified)]
        public string TransactionType { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("loginRequest", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("loginRequest", Namespace="https://payment.fairfinansman.com.tr/")]
    [MessageContract(IsWrapped = false)]
    public partial class LoginRequestaaa
    {
        
        [DataMember(Name = "username")]
        public string Username { get; set; }
        
        [DataMember(Name = "password")]
        public string Password { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("loginResponse", Namespace="https://payment.fairfinansman.com.tr/")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("loginResponse", Namespace="https://payment.fairfinansman.com.tr/")]
    public partial class LoginResponse : BaseApiOutput
    {
        
        [XmlElementAttribute("sessionId", Form=XmlSchemaForm.Unqualified)]
        public string SessionId { get; set; }
    }
}
